name: rugliderqc-test
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=1.1.1
  - netcdf4=1.7.2
  - numpy=2.3.3
  - pandas=2.3.2
  - python=3.12.5
  - scipy=1.16.2
  - xarray=2025.9.0
  - gsw=3.6.20
  - pyco2sys=1.8.3.4
  - pyyaml==6.0.2
